INSERT INTO department (name)
VALUES ("engineering"),
    ("finance"),
    ("marketing"),
    ("sales");

SELECT * FROM DEPARTMENT;

-- engineering department has engineers and project managers and engineering manager
-- finance department has accountants and managers
--  marketing department has product marketing manager, marketing lead
INSERT INTO role (title, salary, department_id)
VALUES ("software engineer", 120000, 1),
    ("engineering project manager", 90000, 1),
    ("engineering department manager", 225000, 1),
    ("accountant", 70000, 2),
    ("accounting lead", 130000, 2),
    ("finance department manager", 215000, 2),
    ("marketing team member", 50000, 3),
    ("marketing lead", 150000, 3),
    ("marketing department manager", 205000, 3),
    ("sales rep", 85000, 4),
    ("sales team lead", 120000, 4),
    ("sales department manager", 200000, 4);

SELECT * FROM ROLE;

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Tony", "Stark", 3, NULL),
    ("Bruce", "Wayne", 6, NULL),
    ("T'Challa", "King", 9, NULL),
    ("Charles", "Xavier", 12, NULL),
    ("Bruce", "Banner", 2, 1),
    ("Peter", "Parker", 2, 1),
    ("Rocket", "Raccoon", 2, 1),
    ("Clark", "Kent", 5, 2),
    ("Dick", "Grayson", 5, 2),
    ("Ororo", "Munroe", 8, 3),
    ("Miles", "Morales", 8, 3),
    ("Damian", "Wayne", 11, 4),
    ("John", "Constantine", 11, 4),
    ("Nick", "Fury", 11, 4),
    ("Kitty", "Pryde", 11, 4),
    ("Diana", "Prince", 7, 11),
    ("John", "Stewart", 1, 6),
    ("Jonn", "Jonzz", 1, 6),
    ("Tandy", "Bowen", 7, 11),
    ("Tyrone", "Johnson", 7, 11),
    ("Selina", "Kyle", 4, 8),
    ("Rachel", "Roth", 1, 6),
    ("Jason", "Todd", 4, 8),
    ("Tim", "Drake", 10, 14),
    ("Tara", "Markov", 1, 6),
    ("Dinah", "Drake", 10, 13),
    ("Harleen", "Quinzel", 7, 11),
    ("Pamela", "Isley", 1, 5),
    ("Zatanna", "Zatara", 10, 13),
    ("Harold", "Jordan", 10, 13),
    ("Barry", "Allen", 1, 5),
    ("Arthur", "Curry", 10, 14),
    ("Victor", "Stone", 1, 5),
    ("Barda", "Free", 4, 9),
    ("Wally", "West", 1, 7),
    ("Bart", "Allen", 1, 7),
    ("Garfield", "Logan", 1, 7),
    ("Jaime", "Reyes", 10, 14),
    ("Roy", "Harper", 10, 15),
    ("Kendra", "Saunders", 10, 12),
    ("Helena", "Bertinelli", 10, 12),
    ("Conner", "Kent", 4, 8),
    ("Steve", "Rogers", 7, 10),
    ("Natasha", "Romanoff", 4, 8),
    ("Clint", "Barton", 4, 9),
    ("James", "Barnes", 7, 10),
    ("Sam", "Wilson", 1, 5),
    ("Thor", "Odinson", 10, 14),
    ("Jean", "Grey", 10, 14),
    ("Raven ", "Darkhölme", 10, 12),
    ("Erik", "Lensher", 4, 9),
    ("Logan", "Howlett", 7, 10),
    ("Wanda", "Maximoff", 10, 12),
    ("Anna-Marie", "LeBeau", 10, 12),
    ("Wayde", "Wilson", 10, 13),
    ("Remy", "LeBeau", 7, 11),
    ("Kurt", "Wagner", 10, 15),
    ("Frank", "Castle", 4, 8),
    ("Janet", "van Dyne", 10, 15),
    ("Hank", "Pym", 1, 5),
    ("Iam", "Groot", 1, 7),
    ("Peter", "Quill", 1, 5),
    ("Stephen", "Strange", 4, 9),
    ("Henry", "McCoy", 1, 7),
    ("Gwen", "Stacy", 1, 6),
    ("Matt", "Murdock", 4, 9),
    ("Jessica", "Jones", 10, 15),
    ("Luke", "Cage", 7, 10),
    ("Daniel", "Rand", 10, 13),
    ("Elektra", "Natchios", 10, 15),
    ("Pietro", "Maximoff", 7, 10),
    ("Neena", "Thurman", 1, 6),
    ("Shang", "Chi", 1, 7),
    ("Jubilation", "Lee", 4, 8);

SELECT * FROM employee;